// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwfxfpyofpomvoyllnat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZnhmcHlvZnBvbXZveWxsbmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzQ4MDksImV4cCI6MjA1ODE1MDgwOX0.tHj8PpzG2JwxLYHhqPDnrX2OhIcRSqbW4buhbW0nXNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);